baseURL = "https://cjbarker.com"
languageCode = "en-us"
title = "CJ Barker"
theme = "cjb"

DefaultContentLanguage = "en"
googleAnalytics = ""
enableRobotsTXT = true

[params]
  favicon = ""
  description = "The last theme you'll ever need. Maybe."
  soundcloud = "https://soundcloud.com/cjbarkbark"
  twitter = "https://twitter.com/cjbarkbark"
  instagram = "https://www.instagram.com/1.21.gigawatts/"
  gitlab = "https://gitlab.com/cjbarker"
  github = "https://github.com/cjbarker"
  linkedin = "https://www.linkedin.com/in/cjbarkbark"
  email = "cj@cjbarker.com"
