# theme.toml template for a Hugo theme
# See https://github.com/spf13/hugoThemes#themetoml for an example

name = "Cjb"
license = "MIT"
licenselink = "https://gitlab.com/cjbarker/cjbarker.com/blob/master/themes/cjb/LICENSE.md"
description = ""
homepage = "https://cjbarker.com/"
tags = ["blogs", "personal"]
features = ["blog", ""]
min_version = 0.20

[author]
  name = "CJ Barker"
  homepage = "https://cjbarker.com"
